# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/kaizenbaiten
spring.datasource.username=kaizenbaiten
spring.datasource.password=kaizenbaiten

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger / springdoc
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always